name: ravenpy-rtd
channels:
- conda-forge
- defaults
dependencies:
  - click
  - matplotlib
#  - netCDF4
#  - xarray
  - wheel
  - dataclasses  # Needed for Python 3.6
  - sphinx
  - nbsphinx
  - pandoc
  - ipython
  - ipykernel
  - jupyter_client
  - pydantic
  - sphinx-click
  - sphinx_rtd_theme
  - sphinx-autoapi
  - sphinxcontrib-napoleon
