name: ravenpy-dev
channels:
  - conda-forge
dependencies:
  - python >=3.10,<3.14
  - raven-hydro >=0.4.0,<1.0
  # - libgcc  # for mixing raven-hydro from PyPI with conda environments
  - affine >=2.4.0
  - cftime >=1.4.1
  - cf_xarray >=0.9.3
  - click >=8.0.0
  - climpred >=2.4.0
  - dask >=2024.8.1
  - fiona >=1.9.0
  - gdal >=3.1
  - geopandas >=1.0
  - h5netcdf >=1.3.0
  - haversine >=2.8.0
  - matplotlib-base >=3.6.0
  - netcdf4 >=1.7.2
  - numpy >=1.25.0
  - owslib >=0.29.1
  - pandas >=2.2.0
  - pint >=0.24.4
  - pydantic >=2.11
  - pydap >=3.4.0,<3.5.5  # pydap 3.5.5 is not currently supported by `xarray` (v2025.3.1)
  - pymetalink >=6.5.2
  - pymbolic >=2024.2
  - pyproj >=3.3.0
  - rasterio
  - rioxarray
  - scipy >=1.11.0,<1.16.0 # See: https://github.com/statsmodels/statsmodels/issues/9584
  - shapely >=2.0.0
  - spotpy >=1.6.1
  - statsmodels >=0.14.2
  - typing_extensions
  - xarray >=2023.11.0,!=2024.10.0
  - xclim >=0.57.0
  - xesmf
  - xsdba >=0.4.0
  - xskillscore
  - zarr >=2.13,<3.0 # FIXME: zarr v3 does not support FSMap like before: https://github.com/zarr-developers/zarr-python/issues/2706
  # Dev tools and testing
  - pip >=25.0
  - black ==25.1.0
  - blackdoc ==0.3.9
  - bump-my-version >=0.32.1
  - click >=8.1.7
  - coverage >=7.5.0
  - filelock >=3.14.0
  - flake8 >=7.1.1
  - flake8-rst-docstrings >=0.3.0
  - flit >=3.10.1,<4.0
  - holoviews
  - hvplot
  - isort ==6.0.0
  - mypy >=1.14.1
  - numpydoc >=1.8.0
  - pooch >=1.8.0
  - pre-commit >=3.5.0
  - pylint >=3.3.0
  - pytest >=8.2.2
  - pytest-cov >=5.0.0
  - pytest-xdist >=3.2.0
  - ruff >=0.9.0
  - setuptools >=71.0
  - tox >=4.24.1
  - watchdog >=4.0.0
