name: ravenpy-rtd
channels:
- conda-forge
- defaults
dependencies:
  - python >=3.8,<3.11
  - autodoc-pydantic
  - click
  - ipykernel
  - ipython
  - jupyter_client
  - matplotlib
  - myst_nb
  - jupytext
  - nbsphinx
#  - netCDF4  # mocked
  - pandoc
  - pydantic
  - sphinx
  - sphinx-autoapi
  - sphinx-click
  - sphinx-codeautolink
  - sphinx-copybutton
  - sphinx_rtd_theme >=1.0
  - sphinxcontrib-napoleon
  - wheel
#  - xarray  # mocked
