name: ravenpy-rtd
channels:
- conda-forge
- defaults
dependencies:
  - python >=3.10,<3.11  # fixed to reduce solver time
  - raven-hydro >=0.3.1,<1.0
  - autodoc-pydantic
  - cairosvg
  - click >=8.0.0
#  - clisops  # mocked
  - gdal >=3.1
# Needed for notebooks/HydroShare_integration.ipynb
# See: https://github.com/CSHS-CWRA/RavenPy/pull/326
#  - "hsclient",
  - ipykernel
  - ipython
  - jupyter_client
  - matplotlib-base
  - myst-nb
  - jupytext
  - nbsphinx
#  - netCDF4  # mocked
  - numpy >=1.23.0,<2.0.0
  - notebook
  - pandoc
  - pydantic >=2.0
  - pygments
  - salib
  - seaborn
  - sphinx >=7.0.0
  - sphinx-autoapi
  - sphinx-click
  - sphinx-codeautolink
  - sphinx-copybutton
  - sphinx-rtd-theme >=1.0
  - sphinxcontrib-svg2pdfconverter
  - typing_extensions
  - wheel
#  - xarray  # mocked
